language: go
go:
- 1.4.2
- 1.5.1
install:
- go get github.com/stretchr/testify/assert
- go get github.com/gorilla/context
- go get github.com/gorilla/sessions
- go get github.com/codegangsta/negroni
- go get github.com/julienschmidt/httprouter
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
- go get
script:
- ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
after_success:
#- mv stormpath-sdk-go.coverprofile coverage.txt && bash <(curl -s https://codecov.io/bash)